### ISSUE TITLE
this is no longer working - Grammarly-Unlock is no longer working

### ISSUE THREAD

**Issue by hmm-star** [blueagler/Grammarly-Unlock#2]
no longer working. please fix it

**Comment by hmm-star** [comment]
hello @blueagler please take a look at it

**Comment by hmm-star** [comment]
?

**Comment by proteuteu** [comment]
@hmm-star you need to install the ublock origin extension for the "show premium suggestions" to work for whatever reason

**Comment by hmm-star** [comment]
okay i will give it a try

**Comment by hmm-star** [comment]
it worked. thank you

**Comment by proteuteu** [comment]
@hmm-star nice. glad i was of help to ya!

**Comment by blueagler** [comment]
Fixed

**Comment by proteuteu** [comment]
@blueagler thank you so so much!
