### ISSUE TITLE
Premium Suggestion need Ublock Origin to work

### ISSUE THREAD

**Issue by proteuteu** [blueagler/Grammarly-Unlock#3]
I just came across this extension and it's amazing. But i also found out that for whatever reason you need to have the Ublock Origin extension installed as well in order for the "Premium sugggestion feature to work". The creator should look into why this is or just put a disclaimer in the description. Hope this helps!

**Comment by hmm-star** [comment]
thank you so much for your suggestion. The extension worked with uBlock origin.

**Comment by proteuteu** [comment]
@hmm-star no problem mate, you're welcome :3

**Comment by jaySantowski** [comment]
What OS are y'all working with? I got the extension working on my home PC that's on windows 10 and it works fine but i cant get it to work on my windows 11 laptop. I tried downloading ublock origin but it didnt do anything. Thanks

**Comment by jaySantowski** [comment]
Update: Got home from class and it looks like they've pushed an update so it isn't even working on my home pc now. Not sure if there's a good solution now because I have ublock on my home pc.

**Comment by hmm-star** [comment]
not working for me now too. I hope @blueagler  will look into this issue soon.

**Comment by blueagler** [comment]
Fixed

**Comment by jaySantowski** [comment]
Thank you blueagler you are a god among men

**Comment by hmm-star** [comment]
@blueagler is legendary

**Comment by proteuteu** [comment]
@blueagler working like a charm now, I cannot fully express how appreciated I'm feeling towards you right now! I will definitely send you some donation in the near future. Wish you the best and here's hoping that you will keep the updates coming if the extension break again.
