### ISSUE TITLE
YOU ARE THE GOAT

### ISSUE THREAD

**Issue by EdwardDK** [blueagler/Grammarly-Unlock#4]
THANKYOU SO MUCH FOR THE GRAMMARLY UPDATE. SUH A GOOD TOOL, LOVE USING IT FOR SCHOOL ESPECIALLY THE FREE TOOL. 

Kinda annoying when it tells you to fix it yourself, maybe you can make it so that it acutally fixes the mistake (I only get the auto fix sometimes)

**Comment by jblqc** [comment]
Hi, I cant seem to use the premium suggestion

**Comment by SehajDxstiny** [comment]
> Hi, I cant seem to use the premium suggestion

same

**Comment by proteuteu** [comment]
@SehajDxstiny @jblqc download version 0.0.4 and maybe try using it with the Ublock Origin extension

**Comment by yowhataa** [comment]
Hi, can someone teach me how to add this/use this?
The instructions weren't clear on how to do so

**Comment by proteuteu** [comment]
@yowhataa 
1. Download "Grammarly.Unlock.Chrome.v0.0.4.zip" from the "Releases" page on the left
2. Extract it using Windows or software such as 7zip, winrar,...
3. Open your browser (Google Chrome, Microsoft Edge,....) -> 3 dots hamburger menu on the top right corner -> Extensions -> Manage Extensions
4. There you can see an option called: "Load unpacked" or something along the line, click on it and choose the folder you just extracted in step 2
.
That's basically it, if the premium suggestions is not showing for you like those above then you might want to go to this link and install the Ublock Origin extension for your browser: https://chromewebstore.google.com/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm

**Comment by blueagler** [comment]
Done
