### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by mightydevourer** [blueagler/Grammarly-Unlock#5]
it doesn't show any suggestion, i tried downloading ublock as one of the fellow member suggested, but it still is not working.

**Comment by proteuteu** [comment]
@mightydevourer still working like a charm for me on Microsoft Edge Version 124.0.2478.80 (Official build) (64-bit). Maybe try checking your browser and extensions for updates.

**Comment by mightydevourer** [comment]
@proteuteu how can i add the grammarly zip into microsoft i dont use microsoft idk

**Comment by proteuteu** [comment]
@mightydevourer 
1. Download "Grammarly.Unlock.Chrome.v0.0.4.zip" from the "Releases" page on the left
2. Extract it using Windows or software such as 7zip, winrar,...
3. Open your browser (Google Chrome, Microsoft Edge,....) -> 3 dots hamburger menu on the top right corner -> Extensions -> Manage Extensions
4. There you can see an option called: "Load unpacked" or something along the line, click on it and choose the folder you just extracted in step 2
.
That's basically it, if the premium suggestions is not showing for you like those above then you might want to go to this link and install the Ublock Origin extension for your browser: https://chromewebstore.google.com/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm

**Comment by mightydevourer** [comment]
@proteuteu I think its a problem with ublock. it's loading very slowly. it only shows a 4 percent advancement in the blocked on this page and it's not advancing

**Comment by mightydevourer** [comment]
@proteuteu do you know how can i get it to load faster? its been five minutes and only 9% has been loaded

**Comment by mightydevourer** [comment]
nvm, its not loading one bit.
