### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by mightydevourer** [blueagler/Grammarly-Unlock#6]
it's not working even after downloading ublock. the problem is with ublcok it's not loading. i need Grammarly so much, I'm writing this thing for a novel and i need its suggestions, what I wrote is around 40k characters, here's my discord "mightydevourer" I can send a file of the thing so that he can apply all suggestions (idrc ill reread it afterwards) and then send it back in another file? so can anyone do it?(you do not have to do it)

**Comment by mightydevourer** [comment]
@blueagler fellow brother, do you have any method for it to work? I urgently need it.

**Comment by blueagler** [comment]
Done
